name: Zizmor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  quality:
    permissions:
      contents: read
    uses: $/.github/workflows/tox-check-reusable.yml
    with:
      tox_env: zizmor
